### ISSUE TITLE
GPU Config file error

### ISSUE THREAD

**Issue by bhargavravat** [3DiVi/face-sdk#2]
facerec exception catched: 'Error 'Invalid license for recognizer. No GPU support.', error code: 0x0f2fc207. wrap code: 0x0d33c4f6.' code: f2fc207

**Comment by ASinkov** [comment]
@bhargavravat It requires a separate license for the use of GPU. Please contact alexbart@3divi.com

**Comment by ASinkov** [comment]
@bhargavravat did we solve your question?

**Comment by ASinkov** [comment]
This issue is to be closed due to long time now response. Please feel free to contact us again or reopen the issue if this issue persist.
