### ISSUE TITLE
File size is wrong

### ISSUE THREAD

**Issue by dominota** [3DiVi/face-sdk#3]
Zip file size is wrong, for example, windows_x86_64.zip is only 14 bytes

**Comment by ASinkov** [comment]
@dominota, to download the archives, you need to use git or download the full distribution kit for the required platform from http://download.3divi.com/facesdk/archives/latest.html. See instructions - https://github.com/3DiVi/face-sdk#getting-started

**Comment by ASinkov** [comment]
@dominota could you download the distribution?

**Comment by ASinkov** [comment]
This issue is to be closed due to long time now response. Please feel free to contact us again or reopen the issue if this issue persist.
