### ISSUE TITLE
Unable to load DLL 'facerec.dll'

### ISSUE THREAD

**Issue by dominota** [3DiVi/face-sdk#4]
I got this error:
Build Visual Studio in x64 mode, FaceSDK 3.6
Unable to load DLL 'facerec.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

**Comment by ASinkov** [comment]
Are you compiling a demo of the app from https://github.com/3DiVi/face-sdk/tree/master/examples/csharp?

**Comment by dominota** [comment]
No,
- I build a new project bases on .Net framework (not .net core)
- The trial key i get by get_license app only valid to 2020-Dec-04, it can not generate a key valid to  2020-Dec-05

**Comment by ASinkov** [comment]
> Copied facerec.dll, sense4.dll to Debug folder

You also need to copy tensorflow.dll to Debug folder

> The trial key i get by get_license app only valid to 2020-Dec-04, it can not generate a key valid to 2020-Dec-05

To obtain a trial license, you need to fill out the form https://face.3divi.com/products/face_sdk/face_sdk_trial (see https://github.com/3DiVi/face-sdk#getting-started). With the get_license app, you can only get an unsigned license that will be invalid (get_license app isn't intended for obtaining a trial license)

**Comment by dominota** [comment]
@ASinkov yes, copied tensorflow.dll too, i can not get it works

**Comment by ASinkov** [comment]
@dominota try to copy all `*dll` files from the `bin` directory

**Comment by ASinkov** [comment]
@dominota did this solve the problem?

**Comment by ASinkov** [comment]
This issue is to be closed due to long time now response. Please feel free to contact us again or reopen the issue if this issue persist.
