### ISSUE TITLE
Depth/Distance Value

### ISSUE THREAD

**Issue by rexn8r** [3DiVi/face-sdk#6]
Hi

Is it possible to get depth or distance value in ft or meter of a face or person detected via your SDK?

thanks
rex

**Comment by leonid-leshukov** [comment]
Hi @rexn8r, thank you for your interest in 3DiVi Face SDK. 
It is possible to get size of face (in pixels), but our SDK doesn't provide distance to the detected faces.
Could you please describe the details of your task/project, to be able to advise a solution. Feel free to reach us using email support-facesdk@3divi.com or in this thread.

**Comment by rexn8r** [comment]
hi @leonid-leshukov 

thanks for your response. 

I am looking to use person demographics information i.e. age and gender along with distance measurements to display custom message on a digital screen.

the message will be displayed based on age and/or gender along with person's proximity to the digital screen. Also the solution should be able to detect multiple faces and infer the information.

thanks
rex

**Comment by leonid-leshukov** [comment]
@rexn8r, I think it is possible to use size of face in pixels to approximate distance from camera to face.  You could define multiple ranges, for example (0-30px, 30-100px, 100px and bigger), and show specific content for every range. You could determine exact bounds of ranges by experimental way.
